reply:
  enable: true
  rules:
    - filter:
        unmatch: ant-design-issue-helper
      action:
        comment: Your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design?repo=ant-design) to create an issue, thank you!
        label: invalid
        close: true
    - filter:
        matchTitle: (官网|网站|mobile ant design|mobile.ant.design|ant design|ant.design|pro).*(挂了|无法访问|不能访问|访问不了|出问题|打不开|登不上|can't open|can not open|can not be reached|can't be reached)
      action:
        comment: |
          Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
          ## 官网
          * Ant Design: https://ant.design
          * Ant Design Pro: https://pro.ant.design
          * Ant Design Mobile: https://mobile.ant.design
          * Ant Motion: https://motion.ant.design
          ## 国内镜像
          * Ant Design: http://ant-design.gitee.io
          * Ant Design Pro: http://ant-design-pro.gitee.io
          * Ant Design Mobile: http://antd-mobile.gitee.io
          * Ant Motion: http://ant-motion.gitee.io
assign:
  enable: true
  rules:
    - filter: 
        match: ant-design-issue-helper
      assignees:
       - yesmeck
      random: true
release:
  enable: true
  files:
    - path: 'CHANGELOG.en-US.md'
      skip: ^`
    - path: 'CHANGELOG.zh-CN.md'
      skip: ^`
    - filter:
replyLabel: 
  rules:
    - filter:
        match: Need Reproduce
      action:
        comment: Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
